services:
  nginx_server:
    image: openresty/openresty:alpine
    container_name: fake-server
    ports:
      - "${MY_PORT}:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    environment:
      - "NGINX_LOGS_STDOUT=1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
